Repository keepassxreboot/keepassxc-browser, pull requests merged in 2018-06, with the labels that each got.

#151 Fix save domain only option
  keepassxc-browser/keepassxc-browser.js
Labels: bug

#154 Fix showing credential update popup
  keepassxc-browser/background/browserAction.js
  keepassxc-browser/background/init.js
  keepassxc-browser/background/keepass.js
  keepassxc-browser/options/options.js
  keepassxc-browser/popups/popup_remember.js
Labels: bug

#164 Improve detection of username fields
  keepassxc-browser/keepassxc-browser.js
Labels: enhancement

#166 MutationObserver optimizations
  keepassxc-browser/keepassxc-browser.js
Labels: enhancement

#182 Add check to page tab ID
  keepassxc-browser/background/page.js
Labels: bug

#185 Ignore comment nodes
  keepassxc-browser/keepassxc-browser.js
Labels: enhancement

#189 Ignore search fields
  keepassxc-browser/keepassxc-browser.js
Labels: bug

#194 Disable single inputs
  keepassxc-browser/keepassxc-browser.js
Labels: bug

#196 Add check function for site ignore settings
  keepassxc-browser/keepassxc-browser.js
Labels: bug

#198 Fix getInputs()
  keepassxc-browser/keepassxc-browser.js
Labels: bug

#199 Fix #196 regression: input field detection broken
  keepassxc-browser/keepassxc-browser.js
Labels: bug, high priority

#207 Fix undefined check
  keepassxc-browser/background/browserAction.js
Labels: bug
