Repository keepassxreboot/keepassxc-browser, pull requests merged in 2018-12, with the labels that each got.

#343 Retrieve credentials with HTTP Basic Auth option added
  keepassxc-browser/background/httpauth.js
  keepassxc-browser/background/keepass.js
  keepassxc-protocol.md
Labels: enhancement

#320 refactor: return a promise instead of using a callback function
  keepassxc-browser/keepassxc-browser.js
Labels: enhancement

#314 Make input field type detection case insensitive
  keepassxc-browser/keepassxc-browser.js
Labels: bug

#325 Remove whitespaces from translation file
  keepassxc-browser/_locales/en/messages.json
  keepassxc-browser/options/options.html
  keepassxc-browser/popups/popup.html
  keepassxc-browser/popups/popup_httpauth.html
  keepassxc-browser/popups/popup_login.html
  keepassxc-browser/popups/popup_multiple-fields.html
  keepassxc-browser/popups/popup_remember.html
Labels: i18n, user experience

#333 New key icon
  keepassxc-browser/_locales/en/messages.json
  keepassxc-browser/icons/key.svg
  keepassxc-browser/keepassxc-browser.css
  keepassxc-browser/manifest.json
  keepassxc-browser/options/options.css
  keepassxc-browser/options/options.html
Labels: user experience

#338 Enable all features when adding site manually to Site Preferences
  keepassxc-browser/options/options.js
Labels: enhancement

#309 Fix unlocking the database
  keepassxc-browser/background/event.js
  keepassxc-browser/background/keepass.js
  keepassxc-browser/keepassxc-browser.js
  keepassxc-browser/popups/popup_httpauth.html
  keepassxc-browser/popups/popup_login.html
  keepassxc-browser/popups/popup_login.js
  keepassxc-browser/popups/popup_multiple-fields.html
  keepassxc-browser/popups/popup_remember.html
Labels: bug
