Repository keepassxreboot/keepassxc-browser, pull requests merged in 2018-05, with the labels that each got.

#114 Add support for ignored sites
  keepassxc-browser/background/browserAction.js
  keepassxc-browser/keepassxc-browser.js
  keepassxc-browser/options/options.html
  keepassxc-browser/options/options.js
  keepassxc-browser/popups/popup_remember.html
  keepassxc-browser/popups/popup_remember.js
Labels: new feature

#126 Automatic reload
  keepassxc-browser/background/event.js
  keepassxc-browser/background/init.js
  keepassxc-browser/background/keepass.js
Labels: new feature

#157 Stop querying changed text nodes for children elements
  keepassxc-browser/keepassxc-browser.js
Labels: bug

#153 Credential retrieval fix
  keepassxc-browser/background/event.js
  keepassxc-browser/background/keepass.js
  keepassxc-browser/keepassxc-browser.js
Labels: needs more testing
