Repository keepassxreboot/keepassxc-browser, pull requests merged in 2018-09, with the labels that each got.

#246 Fix ignored elements function
  keepassxc-browser/keepassxc-browser.js
Labels: bug

#252 Added quick filter in popup
  keepassxc-browser/popups/popup.css
  keepassxc-browser/popups/popup_login.html
  keepassxc-browser/popups/popup_login.js
Labels: new feature

#256 Fixed updating credentials from the context menu
  keepassxc-browser/popups/popup_remember.js
Labels: bug

#258 Allows a separate ID key for association
  keepassxc-browser/background/keepass.js
  keepassxc-protocol.md
Labels: bug

#263 New values for element minimum size with isVisible()
  keepassxc-browser/keepassxc-browser.js
Labels: bug

#289 Fix entering username manually
  keepassxc-browser/keepassxc-browser.js
Labels: bug

#291 Handle single field login forms without error
  keepassxc-browser/keepassxc-browser.js
Labels: bug

#293 Filter out hidden input fields instantly in getInputs()
  keepassxc-browser/keepassxc-browser.js
Labels: bug, enhancement

#296 Update webextension-polyfill
  keepassxc-browser/browser-polyfill.min.js
Labels: bug

#37 Translations
  keepassxc-browser/_locales/en/messages.json
  keepassxc-browser/background/browserAction.js
  keepassxc-browser/background/httpauth.js
  keepassxc-browser/background/init.js
  keepassxc-browser/background/keepass.js
  keepassxc-browser/global.js
  keepassxc-browser/keepassxc-browser.js
  keepassxc-browser/manifest.json
  keepassxc-browser/options/options.html
  keepassxc-browser/popups/popup.html
  keepassxc-browser/popups/popup_httpauth.html
  keepassxc-browser/popups/popup_login.html
  keepassxc-browser/popups/popup_multiple-fields.html
  keepassxc-browser/popups/popup_remember.html
  keepassxc-browser/popups/popup_remember.js
  keepassxc-browser/translate.js
Labels: help wanted
