Repository keepassxreboot/keepassxc-browser, pull requests merged in 2019-10, with the labels that each got.

#630 Fix connection issues
  keepassxc-browser/background/init.js
  keepassxc-browser/background/keepass.js
  keepassxc-browser/popups/popup.css
  keepassxc-browser/popups/popup.html
  keepassxc-browser/popups/throbber.gif
Labels: bug

#620 Fix update button from Credential Banner
  keepassxc-browser/content/keepassxc-browser.js
Labels: bug

#632 Fix await with TOTP fill, code cleaning
  keepassxc-browser/background/page.js
  keepassxc-browser/content/autocomplete.js
  keepassxc-browser/content/banner.js
  keepassxc-browser/content/define.js
  keepassxc-browser/content/keepassxc-browser.js
  keepassxc-browser/content/pwgen.js
  keepassxc-browser/content/sites.js
  keepassxc-browser/content/ui.js
  keepassxc-browser/content/username-field.js
  keepassxc-browser/global.js
Labels: bug

#637 Add undefined type to the input field list
  keepassxc-browser/content/keepassxc-browser.js
Labels: bug

#638 Fix reseting association state
  keepassxc-browser/background/keepass.js
Labels: bug

#635 Fixed popupUpdateAvailable tense
  keepassxc-browser/_locales/en/messages.json
Labels: i18n

#641 Update hashlist when connecting databases
  keepassxc-browser/options/options.js
Labels: bug

#642 Import/Export settings
  keepassxc-browser/_locales/en/messages.json
  keepassxc-browser/options/options.html
  keepassxc-browser/options/options.js
Labels: new feature

#646 Clean functions returning Promise
  keepassxc-browser/background/event.js
  keepassxc-browser/content/autocomplete.js
  keepassxc-browser/content/keepassxc-browser.js
Labels: bug

#647 Do not overwrite keyRing element with itself
  keepassxc-browser/background/keepass.js
Labels: bug
