Repository keepassxreboot/keepassxc-browser, pull requests merged in 2019-01, with the labels that each got.

#369 Fixes to keepassxc-protocol
  keepassxc-protocol.md
Labels: documentation

#349 Disable browserAction update loop
  keepassxc-browser/background/browserAction.js
  keepassxc-browser/background/init.js
Labels: enhancement

#376 Fix version comparison
  keepassxc-browser/background/keepass.js
Labels: bug, high priority

#365 Remove aria-hidden check
  keepassxc-browser/keepassxc-browser.js
Labels: bug, user experience

#371 Fix race conditions
  keepassxc-browser/keepassxc-browser.js
  keepassxc-browser/manifest.json
  keepassxc-browser/requests.js
Labels: bug

#361 fix #360 add `Show more` btn for pwd fields
  keepassxc-browser/_locales/en/messages.json
  keepassxc-browser/keepassxc-browser.js
Labels: new feature

#392 Clearer error messages
  keepassxc-browser/_locales/en/messages.json
  keepassxc-browser/popups/popup.html
Labels: enhancement
