Repository keepassxreboot/keepassxc-browser, pull requests merged in 2020-04, with the labels that each got.

#832 Fix auto-reconnect with Windows
  keepassxc-browser/background/keepass.js
Labels: bug, platform: Windows

#843 Check undefined when saving credentials
  keepassxc-browser/content/banner.js
Labels: bug

#851 Check for CSS opacity
  keepassxc-browser/content/keepassxc-browser.js
Labels: bug

#844 Fix TOTP field maxLength comparison & do not override TOTP icon
  keepassxc-browser/content/totp-field.js
  keepassxc-browser/content/username-field.js
Labels: bug

#853 Translate Lock database text
  keepassxc-browser/_locales/en/messages.json
  keepassxc-browser/popups/popup.html
  keepassxc-browser/popups/popup_httpauth.html
  keepassxc-browser/popups/popup_login.html
  keepassxc-browser/popups/popup_multiple-fields.html
Labels: i18n

#864 Change HTTP Basic Auth help text
  keepassxc-browser/_locales/en/messages.json
Labels: i18n, user experience

#859 Choose custom TOTP field
  keepassxc-browser/_locales/en/messages.json
  keepassxc-browser/content/define.js
  keepassxc-browser/content/keepassxc-browser.js
  keepassxc-browser/css/define.css
Labels: needs more testing, new feature

#863 Ignore banner on tab change
  keepassxc-browser/background/event.js
  keepassxc-browser/background/page.js
Labels: bug

#865 Simplify the options page CSS
  keepassxc-browser/options/options.css
  keepassxc-browser/options/shortcuts.css
  keepassxc-browser/options/shortcuts.js
Labels: bug

#836 Ignore main HTML element from MutationObserver
  keepassxc-browser/content/keepassxc-browser.js
Labels: bug

#845 Clarify key pair usages in protocol description
  keepassxc-protocol.md
Labels: documentation

#867 Change the wording of connected databases text
  keepassxc-browser/_locales/en/messages.json
Labels: i18n

#840 fix autocomplete position when body position is relative
  keepassxc-browser/content/autocomplete.js
  keepassxc-browser/content/ui.js
Labels: bug

#871 Update README
  README.md
Labels: documentation

#872 Simplify options saving process
  keepassxc-browser/options/options.js
Labels: enhancement

#874 Purecss compat - force letter-spacing
  keepassxc-browser/css/autocomplete.css
  keepassxc-browser/css/notification.css
Labels: bug
