Repository keepassxreboot/keepassxc-browser, pull requests merged in 2020-02, with the labels that each got.

#767 Redirect allowance
  keepassxc-browser/_locales/en/messages.json
  keepassxc-browser/background/event.js
  keepassxc-browser/background/init.js
  keepassxc-browser/background/page.js
  keepassxc-browser/content/keepassxc-browser.js
  keepassxc-browser/content/ui.js
  keepassxc-browser/manifest.json
  keepassxc-browser/options/options.css
  keepassxc-browser/options/options.html
  keepassxc-browser/options/options.js
Labels: new feature

#763 Show Credential banner only in the main page
  keepassxc-browser/content/banner.js
Labels: bug

#762 Remove duplicate entries
  keepassxc-browser/background/keepass.js
Labels: bug

#742 Save to Root group if defined without default group
  keepassxc-browser/content/banner.js
Labels: bug

#741 Add submit button type to query with forms
  keepassxc-browser/content/keepassxc-browser.js
Labels: bug

#729 Performance adjustments
  keepassxc-browser/_locales/en/messages.json
  keepassxc-browser/background/page.js
  keepassxc-browser/content/keepassxc-browser.js
  keepassxc-browser/content/ui.js
  keepassxc-browser/options/options.html
Labels: enhancement

#719 Move DOM elements to Shadow DOM
  keepassxc-browser/content/autocomplete.js
  keepassxc-browser/content/banner.js
  keepassxc-browser/content/pwgen.js
  keepassxc-browser/content/totp-field.js
  keepassxc-browser/content/ui.js
  keepassxc-browser/content/username-field.js
  keepassxc-browser/css/pwgen.css
  keepassxc-browser/manifest.json
Labels: new feature

#723 Use the autocomplete attribute as a hint
  keepassxc-browser/content/keepassxc-browser.js
Labels: enhancement

#773 Fix import settings check
  keepassxc-browser/options/options.js
Labels: bug

#779 Ignore input fields with readOnly set
  keepassxc-browser/content/keepassxc-browser.js
Labels: bug

#739 Show the group name in autocomplete
  keepassxc-browser/_locales/en/messages.json
  keepassxc-browser/background/page.js
  keepassxc-browser/content/keepassxc-browser.js
  keepassxc-browser/options/options.html
Labels: new feature

#780 Fixes for 1.5.5
  keepassxc-browser/content/banner.js
  keepassxc-browser/content/keepassxc-browser.js
Labels: bug

#786 TOTP icon improvements
  keepassxc-browser/content/totp-field.js
Labels: enhancement

#772 UI redesign
  .eslintrc
  keepassxc-browser/_locales/en/messages.json
  keepassxc-browser/background/keepass.js
  keepassxc-browser/bootstrap/bootstrap.min.css
  keepassxc-browser/bootstrap/bootstrap.min.js
  keepassxc-browser/bootstrap/jquery-3.4.1.min.js
  keepassxc-browser/css/banner.css
  keepassxc-browser/css/colors.css
  keepassxc-browser/css/notification.css
  keepassxc-browser/fonts/fork-awesome.min.css
  keepassxc-browser/fonts/forkawesome-webfont.woff2
  keepassxc-browser/fonts/glyphicons-halflings-regular.eot
  keepassxc-browser/fonts/glyphicons-halflings-regular.svg
  keepassxc-browser/fonts/glyphicons-halflings-regular.ttf
  keepassxc-browser/fonts/glyphicons-halflings-regular.woff
  keepassxc-browser/fonts/glyphicons-halflings-regular.woff2
  keepassxc-browser/global.js
  keepassxc-browser/jquery-3.3.1.min.js
  keepassxc-browser/options/bootstrap.min.css
  keepassxc-browser/options/bootstrap.min.js
  keepassxc-browser/options/options.css
  keepassxc-browser/options/options.html
  keepassxc-browser/options/options.js
  keepassxc-browser/options/shortcuts.css
  keepassxc-browser/options/shortcuts.html
  keepassxc-browser/options/shortcuts.js
  keepassxc-browser/popups/popup.css
  keepassxc-browser/popups/popup.html
  keepassxc-browser/popups/popup_httpauth.html
  keepassxc-browser/popups/popup_login.html
  keepassxc-browser/popups/popup_multiple-fields.html
  package-lock.json
  package.json
Labels: user experience

#793 Fix theme switching with Firefox
  keepassxc-browser/options/options.js
Labels: browser: Firefox, bug
