Repository keepassxreboot/keepassxc-browser, pull requests merged in 2020-03, with the labels that each got.

#794 New theme adjustments
  keepassxc-browser/css/autocomplete.css
  keepassxc-browser/css/banner.css
  keepassxc-browser/css/colors.css
  keepassxc-browser/options/options.css
  keepassxc-browser/popups/popup.css
Labels: enhancement

#798 Add ignored types for TOTP field icons
  keepassxc-browser/content/totp-field.js
Labels: bug

#792 Use bootstrap classes
  keepassxc-browser/options/options.css
  keepassxc-browser/options/options.html
  keepassxc-browser/options/options.js
Labels: enhancement, user experience

#810 Seperate card for In/Export
  keepassxc-browser/options/options.html
Labels: user experience

#809 Bug fixes for 1.6.0.
  keepassxc-browser/_locales/en/messages.json
  keepassxc-browser/content/banner.js
  keepassxc-browser/content/keepassxc-browser.js
  keepassxc-browser/content/ui.js
  keepassxc-browser/content/username-field.js
  keepassxc-browser/options/options.html
Labels: bug

#808 Add menu icons
  keepassxc-browser/options/options.html
Labels: user experience

#814 Update datetime on reconnect
  keepassxc-browser/background/keepass.js
  keepassxc-browser/manifest.json
  keepassxc-browser/options/options.js
Labels: bug

#817 Disable group name settings with older versions
  keepassxc-browser/options/options.html
  keepassxc-browser/options/options.js
Labels: user experience

#816 Rename root CSS names
  keepassxc-browser/css/autocomplete.css
  keepassxc-browser/css/banner.css
  keepassxc-browser/css/colors.css
  keepassxc-browser/css/pwgen.css
  keepassxc-browser/manifest.json
  keepassxc-browser/options/options.css
  keepassxc-browser/options/shortcuts.css
  keepassxc-browser/popups/popup.css
Labels: bug, user experience

#821 Fix TOTP negative check too strict for (zip|postal)code
  keepassxc-browser/content/totp-field.js
Labels: bug

#823 Fix range input type saving with Firefox
  keepassxc-browser/options/options.js
Labels: bug

#828 Fix default group saving
  keepassxc-browser/manifest.json
  keepassxc-browser/options/options.html
  keepassxc-browser/options/options.js
Labels: bug, high priority
