Repository keepassxreboot/keepassxc-browser, pull requests merged in 2021-06, with the labels that each got.

#1349 Ignore prereleases on update check
  keepassxc-browser/background/keepass.js
Labels: user experience

#1317 Allow file:// protocol in site preferences
  keepassxc-browser/_locales/en/messages.json
  keepassxc-browser/common/global.js
  keepassxc-browser/options/options.html
  keepassxc-browser/options/options.js
Labels: enhancement, new feature

#1350 TOTP filling fixes
  keepassxc-browser/content/keepassxc-browser.js
Labels: bug, needs more testing
