Repository keepassxreboot/keepassxc-browser, pull requests merged in 2021-11, with the labels that each got.

#1439 Add scrolling to autocomplete list
  keepassxc-browser/css/autocomplete.css
Labels: enhancement

#1440 Settings page: load the theme earlier to prevent a white flash
  keepassxc-browser/manifest.json
  keepassxc-browser/options/options.html
  keepassxc-browser/options/options.js
Labels: enhancement

#1429 Fix Apple login page
  keepassxc-browser/common/sites.js
  keepassxc-browser/content/ui.js
Labels: bug

#1443 Do not select the contents of the text field when there are no credentials
  keepassxc-browser/content/autocomplete.js
Labels: enhancement

#1438 Do not autofill the password when Tab is pressed if the list is closed
  keepassxc-browser/content/autocomplete.js
Labels: bug

#1445 Add Twitter to Predefined Sites
  keepassxc-browser/common/sites.js
  keepassxc-browser/content/totp-field.js
Labels: bug

#1447 Fix interfering mouse events when dragging content
  keepassxc-browser/content/ui.js
Labels: bug, high priority

#1448 Upgrade version
  CHANGELOG
  keepassxc-browser/manifest.json
  package-lock.json
  package.json
Labels: high priority

#1466 Add missing translations
  keepassxc-browser/_locales/bg/messages.json
  keepassxc-browser/_locales/et/messages.json
  keepassxc-browser/_locales/he/messages.json
  keepassxc-browser/_locales/nl/messages.json
  keepassxc-browser/_locales/ro/messages.json
  keepassxc-browser/_locales/sl/messages.json
Labels: i18n

#1465 Add inputMode check for 2FA field detection
  keepassxc-browser/content/totp-field.js
Labels: bug

#1470 Add minimum font size to autocomplete menu
  keepassxc-browser/css/autocomplete.css
Labels: bug
