Repository keepassxreboot/keepassxc-browser, pull requests merged in 2021-07, with the labels that each got.

#1363 Fix filling TOTP on Apple login page
  keepassxc-browser/content/keepassxc-browser.js
Labels: bug

#1376 Fix shadowSelectorAll check
  keepassxc-browser/content/keepassxc-browser.js
Labels: browser: Firefox, bug

#1368 Check for form opacity
  keepassxc-browser/content/keepassxc-browser.js
  keepassxc-browser/content/ui.js
Labels: bug

#1374 Added more dispatchEvents to fill()
  keepassxc-browser/content/pwgen.js
Labels: bug

#1351 Fix form detection from style attribute
  keepassxc-browser/content/keepassxc-browser.js
  keepassxc-browser/content/ui.js
Labels: bug

#1380 Revert form visibility check
  keepassxc-browser/content/keepassxc-browser.js
  keepassxc-browser/manifest.json
  package.json
Labels: bug, high priority
