Repository keepassxreboot/keepassxc-browser, pull requests merged in 2021-04, with the labels that each got.

#1294 Fix autocomplete menu with keyboard
  keepassxc-browser/content/autocomplete.js
Labels: bug

#1290 Fix id and name check for form
  keepassxc-browser/content/keepassxc-browser.js
Labels: bug

#1296 Fix filling from popup
  keepassxc-browser/content/keepassxc-browser.js
  keepassxc-browser/manifest.json
  package.json
Labels: bug

#1301 Add "2fpin" to acceptedOTPFields to fix #1291
  keepassxc-browser/content/totp-field.js
Labels: enhancement

#1299 Improve eBay login flow
  keepassxc-browser/common/sites.js
  keepassxc-browser/content/keepassxc-browser.js
Labels: bug

#1304 Switch from index to uuid
  keepassxc-browser/content/credential-autocomplete.js
  keepassxc-browser/content/keepassxc-browser.js
  keepassxc-browser/manifest.json
  package.json
Labels: bug, needs more testing
