Repository keepassxreboot/keepassxc-browser, pull requests merged in 2022-05, with the labels that each got.

#1632 Add link to Troubleshooting Guide to README
  README.md
Labels: documentation

#1628 Update acceptedOTPFields
  keepassxc-browser/content/totp-field.js
Labels: enhancement

#1621 Fix setting icon to all tabs
  keepassxc-browser/background/browserAction.js
Labels: bug

#1571 Adjust the popup size when needed. Change upper row buttons to icons.
  keepassxc-browser/icons/custom_login_fields.svg
  keepassxc-browser/manifest.json
  keepassxc-browser/popups/popup.css
  keepassxc-browser/popups/popup.html
  keepassxc-browser/popups/popup.js
  keepassxc-browser/popups/popup_functions.js
  keepassxc-browser/popups/popup_httpauth.html
  keepassxc-browser/popups/popup_httpauth.js
  keepassxc-browser/popups/popup_login.html
  keepassxc-browser/popups/popup_login.js
Labels: bug, user experience

#1490 Show gray icon when no credentials are available
  keepassxc-browser/content/keepassxc-browser.js
  keepassxc-browser/content/ui.js
  keepassxc-browser/content/username-field.js
  keepassxc-browser/icons/keepassxc-dark.svg
Labels: new feature

#1634 Prevent Cross-Origin requests to KeePassXC
  keepassxc-browser/content/keepassxc-browser.js
Labels: bug, security

#1547 Add support for traversing child elements
  keepassxc-browser/content/observer-helper.js
Labels: bug

#1580 Allow filling password for non-detected fields and combinations
  keepassxc-browser/content/fill.js
  keepassxc-browser/content/keepassxc-browser.js
Labels: bug
