Repository keepassxreboot/keepassxc-browser, pull requests merged in 2022-06, with the labels that each got.

#1637 Prevent endless loops with Auto-Submit
  keepassxc-browser/background/event.js
  keepassxc-browser/background/page.js
  keepassxc-browser/content/fill.js
Labels: new feature

#1441 Sort the page uuid first in the list
  keepassxc-browser/_locales/en/messages.json
  keepassxc-browser/background/page.js
  keepassxc-browser/common/global.js
  keepassxc-browser/content/autocomplete.js
  keepassxc-browser/content/keepassxc-browser.js
  keepassxc-browser/options/options.html
  keepassxc-browser/options/options.js
Labels: enhancement

#1643 Set currentTabId in remove tab.
  keepassxc-browser/background/init.js
Labels: bug

#1390 Custom Login Fields banner selector
  .eslintrc
  keepassxc-browser/_locales/en/messages.json
  keepassxc-browser/content/banner.js
  keepassxc-browser/content/custom-fields-banner.js
  keepassxc-browser/content/define.js
  keepassxc-browser/content/fields.js
  keepassxc-browser/content/fill.js
  keepassxc-browser/content/keepassxc-browser.js
  keepassxc-browser/content/ui.js
  keepassxc-browser/content/username-field.js
  keepassxc-browser/css/banner.css
  keepassxc-browser/css/button.css
  keepassxc-browser/css/define.css
  keepassxc-browser/icons/help.svg
  keepassxc-browser/manifest.json
Labels: new feature

#1638 Various fixes for 1.8.0 release
  keepassxc-browser/background/client.js
  keepassxc-browser/background/keepass.js
  keepassxc-browser/background/page.js
  keepassxc-browser/common/sites.js
  keepassxc-browser/content/fields.js
  keepassxc-browser/content/icons.js
  keepassxc-browser/content/keepassxc-browser.js
  keepassxc-browser/content/observer-helper.js
  keepassxc-browser/content/totp-field.js
  keepassxc-browser/content/ui.js
  keepassxc-browser/popups/popup.css
Labels: bug

#1653 Update changelog for 1.8.0
  CHANGELOG
Labels: documentation

#1655 Update Playwright and fix vulnerabilities
  keepassxc-browser/content/observer-helper.js
  package-lock.json
  package.json
  playwright.config.js
  tests/content-script-tests.mjs
  tests/global-setup.js
  tests/global-teardown.js
Labels: tests
