Repository keepassxreboot/keepassxc-browser, pull requests merged in 2022-11, with the labels that each got.

#1755 Update segmented TOTP detection to work with epicgames.com
  keepassxc-browser/content/fields.js
Labels: bug, 2fa

#1758 Fix enter key issue on Google
  keepassxc-browser/content/autocomplete.js
  keepassxc-browser/css/autocomplete.css
Labels: bug

#1769 Add steamcommunity.com to 2FA exception list
  keepassxc-browser/common/sites.js
Labels: bug, 2fa

#1770 Fix Autocomplete Menu border color on dark theme
  keepassxc-browser/content/autocomplete.js
  keepassxc-browser/css/autocomplete.css
  keepassxc-browser/css/colors.css
Labels: bug, UI/UX

#1756 Update eslint rules, add `.prettierignore` file, fix some formatting, and fix some bugs
  .eslintrc
  .prettierignore
  .prettierrc
  keepassxc-browser/_locales/bg/messages.json
  keepassxc-browser/_locales/cs/messages.json
  keepassxc-browser/_locales/de/messages.json
  keepassxc-browser/_locales/el/messages.json
  keepassxc-browser/_locales/en/messages.json
  keepassxc-browser/_locales/es/messages.json
  keepassxc-browser/_locales/et/messages.json
  keepassxc-browser/_locales/fi/messages.json
  keepassxc-browser/_locales/fr/messages.json
  keepassxc-browser/_locales/he/messages.json
  keepassxc-browser/_locales/hu/messages.json
  keepassxc-browser/_locales/it/messages.json
  keepassxc-browser/_locales/ja/messages.json
  keepassxc-browser/_locales/ko/messages.json
  keepassxc-browser/_locales/la/messages.json
  keepassxc-browser/_locales/my/messages.json
  keepassxc-browser/_locales/nl/messages.json
  keepassxc-browser/_locales/nl_NL/messages.json
  keepassxc-browser/_locales/pl/messages.json
  keepassxc-browser/_locales/pt/messages.json
  keepassxc-browser/_locales/pt_BR/messages.json
  keepassxc-browser/_locales/pt_PT/messages.json
  keepassxc-browser/_locales/ro/messages.json
  keepassxc-browser/_locales/ru/messages.json
  keepassxc-browser/_locales/sl/messages.json
  keepassxc-browser/_locales/sv/messages.json
  keepassxc-browser/_locales/tr/messages.json
  keepassxc-browser/_locales/uk/messages.json
  keepassxc-browser/_locales/zh_CN/messages.json
  keepassxc-browser/_locales/zh_TW/messages.json
  keepassxc-browser/background/keepass.js
  keepassxc-browser/background/page.js
  keepassxc-browser/common/global.js
  keepassxc-browser/common/translate.js
  keepassxc-browser/content/autocomplete.js
  keepassxc-browser/content/banner.js
  keepassxc-browser/content/custom-fields-banner.js
  keepassxc-browser/content/fill.js
  keepassxc-browser/content/form.js
  keepassxc-browser/content/observer-helper.js
  keepassxc-browser/manifest.json
  keepassxc-browser/options/options.css
  keepassxc-browser/options/options.html
  keepassxc-browser/options/options.js
  keepassxc-browser/options/shortcuts.html
  keepassxc-browser/popups/popup.css
  keepassxc-browser/popups/popup.html
  keepassxc-browser/popups/popup.js
  keepassxc-browser/popups/popup_httpauth.html
  keepassxc-browser/popups/popup_login.html
  tests/assert.js
  tests/global-setup.js
  tests/global-teardown.js
  tests/tests.html
Labels: enhancement

#1773 Wait for stylesheets to load before displaying shadow DOM elements
  keepassxc-browser/content/autocomplete.js
  keepassxc-browser/content/banner.js
  keepassxc-browser/content/custom-fields-banner.js
  keepassxc-browser/content/totp-field.js
  keepassxc-browser/content/ui.js
  keepassxc-browser/content/username-field.js
Labels: bug, UI/UX
