Repository keepassxreboot/keepassxc-browser, pull requests merged in 2022-01, with the labels that each got.

#1512 Fix removing icon from parent/document
  keepassxc-browser/content/pwgen.js
  keepassxc-browser/content/username-field.js
  keepassxc-browser/css/pwgen.css
Labels: bug

#1511 Autocomplete search feature
  keepassxc-browser/content/autocomplete.js
  keepassxc-browser/content/credential-autocomplete.js
  keepassxc-browser/content/keepassxc-browser.js
  keepassxc-browser/content/totp-autocomplete.js
  keepassxc-browser/css/autocomplete.css
Labels: new feature

#1518 Scroll login list instead of the whole popup body
  keepassxc-browser/popups/popup.css
Labels: user experience

#1510 Content script refactoring for 1.8.0
  .eslintrc
  keepassxc-browser/background/event.js
  keepassxc-browser/background/init.js
  keepassxc-browser/content/credential-autocomplete.js
  keepassxc-browser/content/fields.js
  keepassxc-browser/content/fill.js
  keepassxc-browser/content/form.js
  keepassxc-browser/content/icons.js
  keepassxc-browser/content/keepassxc-browser.js
  keepassxc-browser/content/observer-helper.js
  keepassxc-browser/content/pwgen.js
  keepassxc-browser/content/totp-autocomplete.js
  keepassxc-browser/content/totp-field.js
  keepassxc-browser/content/username-field.js
  keepassxc-browser/manifest.json
  package-lock.json
  package.json
Labels: refactor

#1520 Refactor background scripts for 1.8.0
  .eslintrc
  keepassxc-browser/background/client.js
  keepassxc-browser/background/event.js
  keepassxc-browser/background/keepass.js
  keepassxc-browser/common/global.js
  keepassxc-browser/manifest.json
Labels: refactor

#1525 Fix Google password fill from popup
  keepassxc-browser/common/sites.js
  keepassxc-browser/content/fill.js
Labels: bug

#1530 Fix TOTP fill. Save loginId to tab.
  keepassxc-browser/background/page.js
Labels: bug

#1540 Add debug logging option
  keepassxc-browser/_locales/en/messages.json
  keepassxc-browser/background/browserAction.js
  keepassxc-browser/background/client.js
  keepassxc-browser/background/event.js
  keepassxc-browser/background/httpauth.js
  keepassxc-browser/background/init.js
  keepassxc-browser/background/keepass.js
  keepassxc-browser/background/page.js
  keepassxc-browser/common/global.js
  keepassxc-browser/content/banner.js
  keepassxc-browser/content/fill.js
  keepassxc-browser/content/form.js
  keepassxc-browser/content/keepassxc-browser.js
  keepassxc-browser/content/observer-helper.js
  keepassxc-browser/content/totp-field.js
  keepassxc-browser/content/ui.js
  keepassxc-browser/options/options.html
  keepassxc-browser/popups/popup.js
Labels: new feature

#1551 Update webextension-polyfill from 0.7.0 to 0.8.0
  keepassxc-browser/common/browser-polyfill.min.js
Labels: library update
