Repository keepassxreboot/keepassxc-browser, pull requests merged in 2023-09, with the labels that each got.

#1976 Fix getting combination from Custom Login Fields during credential save
  keepassxc-browser/content/fields.js
  keepassxc-browser/content/keepassxc-browser.js
Labels: bug

#1978 Fix Autocomplete Menu fill on Enter when list is sorted
  keepassxc-browser/content/autocomplete.js
  keepassxc-browser/content/credential-autocomplete.js
  keepassxc-browser/content/totp-autocomplete.js
Labels: bug

#1974 Fill whole combination when Autocomplete Menu is disabled
  keepassxc-browser/content/fill.js
Labels: bug

#1982 Fix Check for updates button response
  keepassxc-browser/background/event.js
Labels: bug

#1981 Fix removing notifications
  keepassxc-browser/content/ui.js
Labels: bug, UI/UX

#1961 Refactor extension messaging
  keepassxc-browser/background/client.js
  keepassxc-browser/background/keepass.js
  keepassxc-browser/manifest.json
Labels: needs more testing, refactor

#1983 Cosmetic fixes
  .eslintrc
  .gitignore
  build.js
  keepassxc-browser/background/browserAction.js
  keepassxc-browser/background/page.js
  keepassxc-browser/content/keepassxc-browser.js
  keepassxc-browser/content/totp-field.js
  keepassxc-browser/content/ui.js
  keepassxc-browser/options/options.html
  keepassxc-browser/options/options.js
  keepassxc-browser/options/shortcuts.html
  keepassxc-browser/popups/popup.css
  keepassxc-browser/popups/popup.html
  keepassxc-browser/popups/popup.js
  keepassxc-browser/popups/popup_functions.js
  keepassxc-browser/popups/popup_httpauth.html
  keepassxc-browser/popups/popup_login.html
  package-lock.json
  package.json
  playwright.config.js
  tests/tests.html
Labels: UI/UX

#1986 Dispatch more events on fill
  keepassxc-browser/content/keepassxc-browser.js
Labels: bug

#1985 Use active element on fillFromCombination()
  keepassxc-browser/content/fill.js
Labels: bug

#1988 Use the first combination if active element is not found
  keepassxc-browser/content/fill.js
Labels: bug

#1989 Fix showing TOTP error message
  keepassxc-browser/content/fill.js
Labels: bug, UI/UX

#1993 Add Patreon to Predefined Sites
  keepassxc-browser/common/sites.js
  keepassxc-browser/content/observer-helper.js
Labels: bug
