Repository keepassxreboot/keepassxc-browser, pull requests merged in 2023-12, with the labels that each got.

#1771 Remove special handling for Firefox overflow/hamburger menu
  keepassxc-browser/popups/popup.css
  keepassxc-browser/popups/popup.html
  keepassxc-browser/popups/popup.js
  keepassxc-browser/popups/popup_functions.js
  keepassxc-browser/popups/popup_httpauth.html
  keepassxc-browser/popups/popup_httpauth.js
  keepassxc-browser/popups/popup_login.html
  keepassxc-browser/popups/popup_login.js
Labels: UI/UX

#2055 Stop pages from being able to style the shadow DOM wrapper div element
  keepassxc-browser/content/autocomplete.js
  keepassxc-browser/content/banner.js
  keepassxc-browser/content/custom-fields-banner.js
  keepassxc-browser/content/totp-field.js
  keepassxc-browser/content/ui.js
  keepassxc-browser/content/username-field.js
Labels: bug, UI/UX

#2054 Small fixes to the options page
  .eslintrc
  README.md
  keepassxc-browser/background/client.js
  keepassxc-browser/options/options.css
  keepassxc-browser/options/options.html
  keepassxc-browser/options/options.js
  tests/.eslintrc
  tests/content-script-tests.mjs
Labels: bug, UI/UX

#2059 Disallow iframes from another domain
  keepassxc-browser/content/keepassxc-browser.js
Labels: bug, security
