Repository keepassxreboot/keepassxc-browser, pull requests merged in 2023-01, with the labels that each got.

#1816 Remove eslint-config-airbnb-base
  .eslintrc
  package-lock.json
  package.json
Labels: library update

#1822 Remove browser.runtime.getBackgroundPage()
  keepassxc-browser/background/event.js
  keepassxc-browser/background/page.js
  keepassxc-browser/popups/popup_functions.js
  keepassxc-browser/popups/popup_httpauth.js
  keepassxc-browser/popups/popup_login.js
Labels: refactor

#1825 Fix extension behavior for Auto-Open
  keepassxc-browser/content/keepassxc-browser.js
Labels: bug

#1827 Fix updating Autocomplete Menu on database close
  keepassxc-browser/content/autocomplete.js
Labels: bug

#1835 Fix login popup change with locked database
  keepassxc-browser/background/browserAction.js
  keepassxc-browser/background/keepass.js
  keepassxc-browser/popups/popup_httpauth.html
  keepassxc-browser/popups/popup_login.html
Labels: bug

#1836 Remove icon input field from the internal list when removing the icon
  keepassxc-browser/content/observer-helper.js
  keepassxc-browser/content/ui.js
Labels: bug

#1842 Increase default redirect value from 1 to 3
  keepassxc-browser/_locales/en/messages.json
  keepassxc-browser/background/page.js
Labels: enhancement

#1841 Do not fill readonly fields
  keepassxc-browser/content/keepassxc-browser.js
Labels: bug
