Repository keepassxreboot/keepassxc-browser, pull requests merged in 2023-02, with the labels that each got.

#1848 Make sure checkUpdateKeePassXC is an integer
  keepassxc-browser/background/event.js
  keepassxc-browser/background/keepass.js
Labels: bug

#1849 Support adf.ly TOTP field
  keepassxc-browser/common/sites.js
Labels: 2fa

#1851 Replace Match Patterns regex with a simpler function
  keepassxc-browser/common/global.js
  keepassxc-browser/common/sites.js
  tests/assert.js
  tests/tests.html
  tests/tests.js
Labels: refactor

#1856 Improve filling from Username Icon
  keepassxc-browser/content/banner.js
  keepassxc-browser/content/keepassxc-browser.js
  keepassxc-browser/content/username-field.js
Labels: bug

#1782 Try harder to prevent false-positive password change banners
  keepassxc-browser/content/form.js
Labels: bug

#1857 Allow force-fill to String Fields even if readonly
  keepassxc-browser/content/fill.js
  keepassxc-browser/content/keepassxc-browser.js
Labels: bug

#1866 Add support for showing Autocomplete Menu on top
  keepassxc-browser/content/autocomplete.js
  keepassxc-browser/css/autocomplete.css
Labels: bug
