Repository keepassxreboot/keepassxc-browser, pull requests merged in 2023-11, with the labels that each got.

#2029 Fix selecting first item on Autocomplete Menu open
  keepassxc-browser/content/autocomplete.js
Labels: bug

#2032 Add eslint to scripts
  .eslintrc
  package.json
Labels: tests

#1987 Upgrade bootstrap for improved dark mode support
  README.md
  keepassxc-browser/bootstrap/bootstrap.min.css
  keepassxc-browser/bootstrap/bootstrap.min.js
  keepassxc-browser/content/ui.js
  keepassxc-browser/css/colors.css
  keepassxc-browser/manifest.json
  keepassxc-browser/options/options.css
  keepassxc-browser/options/options.html
  keepassxc-browser/options/options.js
  keepassxc-browser/options/shortcuts.js
  keepassxc-browser/popups/popup.css
  keepassxc-browser/popups/popup_functions.js
Labels: UI/UX

#2036 Fix Passkey error messages
  keepassxc-browser/_locales/en/messages.json
  keepassxc-browser/background/client.js
Labels: bug, passkeys

#2038 Passkeys: Revert to default values
  keepassxc-browser/content/passkeys-utils.js
Labels: bug, passkeys

#2039 Add Wordpress to Site Preferences
  keepassxc-browser/common/sites.js
Labels: bug

#2042 Passkeys: Use hostname instead of host
  keepassxc-browser/content/passkeys-utils.js
Labels: bug, passkeys
