Repository keepassxreboot/keepassxc-browser, pull requests merged in 2024-05, with the labels that each got.

#2178 Passkeys: Wrap response to PublicKeyCredential
  keepassxc-browser/content/keepassxc-browser.js
  keepassxc-browser/content/passkeys-utils.js
  keepassxc-browser/content/passkeys.js
Labels: passkeys

#2195 Remove obsolete hashed scripts from manifest
  CHANGELOG
  dist/manifest_chromium.json
  dist/manifest_firefox.json
  keepassxc-browser/_locales/ja/messages.json
  keepassxc-browser/manifest.json
  package-lock.json
  package.json
Labels: bug

#2199 Fix XML formatting with Firefox
  keepassxc-browser/content/keepassxc-browser.js
Labels: bug, browser: Firefox

#2152 Fix monochrome icon in Chrome when `colorTheme == 'system'` (MV3 fix)
  .eslintrc
  dist/manifest_chromium.json
  dist/manifest_firefox.json
  keepassxc-browser/background/background_service.js
  keepassxc-browser/background/browserAction.js
  keepassxc-browser/background/offscreen.js
  keepassxc-browser/manifest.json
  keepassxc-browser/offscreen/offscreen.html
  keepassxc-browser/offscreen/offscreen.js
Labels: bug

#2181 Remove duplicate notification
  keepassxc-browser/content/fill.js
Labels: bug

#2206 Passkeys: Remove temporary exceptions
  keepassxc-browser/content/passkeys-utils.js
Labels: passkeys

#2207 Ignore all ports by default in Site Preferences
  keepassxc-browser/common/global.js
Labels: bug
