Repository keepassxreboot/keepassxc-browser, pull requests merged in 2024-12, with the labels that each got.

#2398 Add some predefined sites
  keepassxc-browser/common/sites.js
Labels: bug, non-working site

#2405 Show error notification when database is not connected
  keepassxc-browser/_locales/en/messages.json
  keepassxc-browser/content/fill.js
Labels: new feature

#2411 Add checks for TreeWalker filter
  keepassxc-browser/content/observer-helper.js
Labels: bug

#2418 Remove span element from ignored nodes
  keepassxc-browser/content/observer-helper.js
Labels: bug, non-working site

#2420 Disable passkeys fallback checkbox when needed
  keepassxc-browser/options/options.js
Labels: UI/UX, passkeys

#2416 Fixed values of constants
  keepassxc-browser/content/keepassxc-browser.js
Labels: bug, passkeys
