Repository keepassxreboot/keepassxc-browser, pull requests merged in 2024-10, with the labels that each got.

#2351 Fix Predefined Sites for some pages
  keepassxc-browser/common/sites.js
  keepassxc-browser/content/fields.js
Labels: bug

#2346 Add configuration option for modifying the passkeys default group
  keepassxc-browser/_locales/en/messages.json
  keepassxc-browser/background/keepass.js
  keepassxc-browser/background/page.js
  keepassxc-browser/options/options.html
  keepassxc-browser/options/options.js
  keepassxc-protocol.md
Labels: new feature, passkeys

#2323 Prevent Illegal Invokcation on getPublicKey/getPublicKeyAlgorithm
  keepassxc-browser/content/passkeys.js
Labels: passkeys

#2341 Fix the coordinate shift caused by CSS zoom
  keepassxc-browser/content/autocomplete.js
  keepassxc-browser/content/custom-fields-banner.js
  keepassxc-browser/content/ui.js
Labels: bug

#2356 Add icon offset exception to Royal Bank Canada
  keepassxc-browser/common/sites.js
  keepassxc-browser/content/ui.js
Labels: bug

#2359 Add support for draggable banners
  .eslintrc
  keepassxc-browser/background/event.js
  keepassxc-browser/background/page.js
  keepassxc-browser/common/global.js
  keepassxc-browser/content/autocomplete.js
  keepassxc-browser/content/banner.js
  keepassxc-browser/content/custom-fields-banner.js
  keepassxc-browser/content/passkeys.js
  keepassxc-browser/content/ui.js
  keepassxc-browser/css/banner.css
Labels: new feature

#2361 Fix base translation wording
  keepassxc-browser/_locales/en/messages.json
Labels: i18n

#2360 Better identification for Shadow DOM in Improved Input Field Detection
  keepassxc-browser/content/observer-helper.js
Labels: enhancement, refactor

#2366 Add support for managed settings using 3rdparty policy
  dist/manifest_chromium.json
  dist/manifest_firefox.json
  keepassxc-browser/background/page.js
  keepassxc-browser/managed_storage.json
  keepassxc-browser/manifest.json
Labels: new feature
