Repository keepassxreboot/keepassxc-browser, pull requests merged in 2024-06, with the labels that each got.

#2229 Rename Credential Banner buttons
  keepassxc-browser/_locales/en/messages.json
  keepassxc-browser/content/banner.js
Labels: UI/UX, i18n

#2230 Rename functions to prevent override
  keepassxc-browser/content/passkeys-utils.js
  keepassxc-browser/content/passkeys.js
Labels: bug, passkeys

#2227 Show group name in Credential Banner's menu when updating a credential
  keepassxc-browser/content/keepassxc-browser.js
Labels: bug

#2228 Translation fixes
  keepassxc-browser/_locales/en/messages.json
  keepassxc-browser/content/username-field.js
Labels: i18n

#2197 ✏️ (Context Menu) Consistency with other terms
  keepassxc-browser/_locales/en/messages.json
Labels: work in progress, i18n

#2244 Fix more translations
  keepassxc-browser/_locales/en/messages.json
  keepassxc-browser/content/pwgen.js
  keepassxc-browser/content/totp-field.js
  keepassxc-browser/options/options.html
  keepassxc-browser/popups/popup.html
  keepassxc-browser/popups/popup_httpauth.html
  keepassxc-browser/popups/popup_login.html
Labels: i18n

#2246 Change password fill shortcut with Chrome
  dist/manifest_chromium.json
Labels: bug, browser: Chrome

#2166 Handle iframe URLs correctly
  keepassxc-browser/background/page.js
  keepassxc-browser/content/keepassxc-browser.js
Labels: bug
