Repository keepassxreboot/keepassxc-browser, pull requests merged in 2024-07, with the labels that each got.

#2256 Add "missing" icon size for Firefox
  dist/manifest_firefox.json
Labels: UI/UX

#2119 Refactor design of autocomplete dropdown
  keepassxc-browser/_locales/en/messages.json
  keepassxc-browser/background/page.js
  keepassxc-browser/content/autocomplete.js
  keepassxc-browser/content/credential-autocomplete.js
  keepassxc-browser/content/keepassxc-browser.js
  keepassxc-browser/css/autocomplete.css
  keepassxc-browser/css/colors.css
  keepassxc-browser/options/options.html
Labels: new feature, UI/UX

#2258 Fix showing group name in Autocomplete Menu
  keepassxc-browser/content/keepassxc-browser.js
Labels: bug

#2259 Fix plain text password fill prevention
  keepassxc-browser/content/fill.js
Labels: bug

#2262 Fix credential sorting
  keepassxc-browser/content/keepassxc-browser.js
Labels: bug

#2269 Fix line height with the new Autocomplete Menu
  keepassxc-browser/css/autocomplete.css
Labels: bug, UI/UX

#2270 Remove build script dependency
  build.js
  package-lock.json
  package.json
Labels: dependencies

#2274 Fix setting Autocomplete Menu min-width
  keepassxc-browser/css/autocomplete.css
Labels: bug, UI/UX

#2281 Update Playwright and improve tests
  .gitignore
  keepassxc-browser/common/global.js
  package-lock.json
  package.json
  playwright.config.ts
  tests/content-scripts.spec.ts
  tests/global-setup.js
  tests/global-setup.ts
  tests/global-teardown.js
  tests/global-teardown.ts
  tests/global.spec.ts
  tests/page.spec.ts
  tests/tests.js
Labels: tests

#2287 Fix XML formatting
  dist/manifest_chromium.json
  dist/manifest_firefox.json
  keepassxc-browser/content/keepassxc-browser.js
  keepassxc-browser/manifest.json
Labels: bug

#2293 Add Improved Input Field Detection to Predefined Sites feature
  .eslintrc
  keepassxc-browser/common/sites.js
  keepassxc-browser/content/keepassxc-browser.js
Labels: new feature
