Repository keepassxreboot/keepassxc-browser, pull requests merged in 2024-02, with the labels that each got.

#2106 Do not clear the username field if the entry has no username set
  keepassxc-browser/content/fill.js
Labels: new feature

#2107 Do not allow filling password (only) to plain text fields
  keepassxc-browser/_locales/en/messages.json
  keepassxc-browser/content/fill.js
Labels: new feature, security

#2114 Passkeys: Fixes invalid error message related to Resident Keys
  keepassxc-browser/_locales/en/messages.json
  keepassxc-browser/background/client.js
Labels: bug, passkeys

#1723 Support for Manifest V3
  .eslintrc
  build.js
  dist/manifest_chromium.json
  dist/manifest_firefox.json
  keepassxc-browser/background/background_service.js
  keepassxc-browser/background/browserAction.js
  keepassxc-browser/background/event.js
  keepassxc-browser/background/init.js
  keepassxc-browser/background/keepass.js
  keepassxc-browser/background/page.js
  keepassxc-browser/common/global.js
  keepassxc-browser/common/global_ui.js
  keepassxc-browser/content/keepassxc-browser.js
  keepassxc-browser/options/options.html
  keepassxc-browser/options/options.js
  keepassxc-browser/popups/popup.css
  keepassxc-browser/popups/popup.html
  keepassxc-browser/popups/popup_functions.js
  keepassxc-browser/popups/popup_httpauth.html
  keepassxc-browser/popups/popup_login.html
  keepassxc-browser/popups/popup_login.js
Labels: new feature

#2120 Fix calculation of icon offset
  keepassxc-browser/content/ui.js
Labels: bug, UI/UX

#2125 Show number of credentials in the extension icon
  keepassxc-browser/background/browserAction.js
  keepassxc-browser/background/event.js
  keepassxc-browser/icons/toolbar/colored/icon_new_questionmark.png
  keepassxc-browser/icons/toolbar/colored/icon_new_questionmark.svg
  keepassxc-browser/icons/toolbar/colored/icon_questionmark.png
  keepassxc-browser/icons/toolbar/colored/icon_questionmark.svg
  keepassxc-browser/icons/toolbar/dark/icon_new_questionmark.png
  keepassxc-browser/icons/toolbar/dark/icon_new_questionmark.svg
  keepassxc-browser/icons/toolbar/dark/icon_questionmark.png
  keepassxc-browser/icons/toolbar/dark/icon_questionmark.svg
  keepassxc-browser/icons/toolbar/light/icon_new_questionmark.png
  keepassxc-browser/icons/toolbar/light/icon_new_questionmark.svg
  keepassxc-browser/icons/toolbar/light/icon_questionmark.png
  keepassxc-browser/icons/toolbar/light/icon_questionmark.svg
Labels: new feature, UI/UX

#1966 Remove internal password generator
  .eslintrc
  keepassxc-browser/_locales/en/messages.json
  keepassxc-browser/content/keepassxc-browser.js
  keepassxc-browser/content/pwgen.js
  keepassxc-browser/content/totp-field.js
  keepassxc-browser/content/ui.js
  keepassxc-browser/content/username-field.js
  keepassxc-browser/css/pwgen.css
Labels: refactor
