Repository keepassxreboot/keepassxc-browser, pull requests merged in 2025-05, with the labels that each got.

#2542 Add submit button exception for OpenAI login page
  keepassxc-browser/common/sites.js
Labels: bug

#2548 Fix browser integration doc link id
  README.md
  keepassxc-browser/popups/popup.html
Labels: documentation

#2553 Styling improvements
  keepassxc-browser/_locales/en/messages.json
  keepassxc-browser/options/options.css
  keepassxc-browser/options/options.html
Labels: UI/UX
