Repository keepassxreboot/keepassxc-browser, pull requests merged in 2025-07, with the labels that each got.

#2599 chore(i18n): Fix URL of Transifx
  README.md
Labels: documentation, i18n

#2595 Move privacy to optional permissions
  dist/manifest_chromium.json
  dist/manifest_firefox.json
  keepassxc-browser/background/page.js
  keepassxc-browser/common/global_ui.js
  keepassxc-browser/manifest.json
  keepassxc-browser/options/getting_started.js
  keepassxc-browser/options/options.js
Labels: security

#2600 Update to 1.9.9.1
  CHANGELOG
  dist/manifest_chromium.json
  dist/manifest_firefox.json
  keepassxc-browser/_locales/tr/messages.json
  keepassxc-browser/manifest.json
  package-lock.json
  package.json
Labels: release

#2603 Update CHANGELOG
  CHANGELOG
Labels: release
