Repository keepassxreboot/keepassxc-browser, pull requests merged in 2025-02, with the labels that each got.

#2455 Load managed settings always when found
  keepassxc-browser/background/page.js
Labels: bug

#2454 Add extra check for TOTP field input type
  keepassxc-browser/content/totp-field.js
Labels: bug

#2409 Auto-fill will be applied if related credentials are available
  keepassxc-browser/_locales/en/messages.json
  keepassxc-browser/background/page.js
  keepassxc-browser/content/keepassxc-browser.js
  keepassxc-browser/managed_storage.json
  keepassxc-browser/options/options.html
Labels: new feature

#2464 Update to 1.9.7
  CHANGELOG
  dist/manifest_chromium.json
  dist/manifest_firefox.json
  keepassxc-browser/_locales/bg/messages.json
  keepassxc-browser/_locales/cs/messages.json
  keepassxc-browser/_locales/da/messages.json
  keepassxc-browser/_locales/de/messages.json
  keepassxc-browser/_locales/el/messages.json
  keepassxc-browser/_locales/en_GB/messages.json
  keepassxc-browser/_locales/es/messages.json
  keepassxc-browser/_locales/fi/messages.json
  keepassxc-browser/_locales/fr/messages.json
  keepassxc-browser/_locales/he/messages.json
  keepassxc-browser/_locales/hu/messages.json
  keepassxc-browser/_locales/id/messages.json
  keepassxc-browser/_locales/it/messages.json
  keepassxc-browser/_locales/ja/messages.json
  keepassxc-browser/_locales/ko/messages.json
  keepassxc-browser/_locales/lt/messages.json
  keepassxc-browser/_locales/my/messages.json
  keepassxc-browser/_locales/nb/messages.json
  keepassxc-browser/_locales/nl/messages.json
  keepassxc-browser/_locales/pl/messages.json
  keepassxc-browser/_locales/pt_BR/messages.json
  keepassxc-browser/_locales/pt_PT/messages.json
  keepassxc-browser/_locales/ro/messages.json
  keepassxc-browser/_locales/ru/messages.json
  keepassxc-browser/_locales/sl/messages.json
  keepassxc-browser/_locales/sv/messages.json
  keepassxc-browser/_locales/tr/messages.json
  keepassxc-browser/_locales/uk/messages.json
  keepassxc-browser/_locales/zh_CN/messages.json
  keepassxc-browser/_locales/zh_TW/messages.json
  keepassxc-browser/manifest.json
  package-lock.json
  package.json
Labels: release
