Repository keepassxreboot/keepassxc-browser, pull requests merged in 2025-08, with the labels that each got.

#2644 Update to 1.9.9.2
  CHANGELOG
  dist/manifest_chromium.json
  dist/manifest_firefox.json
  keepassxc-browser/_locales/es/messages.json
  keepassxc-browser/_locales/fr/messages.json
  keepassxc-browser/_locales/it/messages.json
  keepassxc-browser/_locales/pt_BR/messages.json
  keepassxc-browser/_locales/uk/messages.json
  keepassxc-browser/manifest.json
  package-lock.json
  package.json
Labels: release

#2646 Prevent style changes to wrapper divs
  keepassxc-browser/content/autocomplete.js
  keepassxc-browser/content/banner.js
  keepassxc-browser/content/custom-fields-banner.js
  keepassxc-browser/content/ui.js
Labels: bug, security

#2649 Add special error message for untrusted iframes
  keepassxc-browser/_locales/en/messages.json
  keepassxc-browser/content/fill.js
  keepassxc-browser/content/keepassxc-browser.js
Labels: enhancement

#2653 Clear credentials if html/body/form opacity limit is met
  .eslintrc
  keepassxc-browser/background/event.js
  keepassxc-browser/content/form.js
  keepassxc-browser/content/keepassxc-browser.js
  keepassxc-browser/content/ui.js
Labels: bug, security

#2655 Update to 1.9.9.3
  CHANGELOG
  README.md
  dist/manifest_chromium.json
  dist/manifest_firefox.json
  keepassxc-browser/_locales/bg/messages.json
  keepassxc-browser/_locales/cs/messages.json
  keepassxc-browser/_locales/da/messages.json
  keepassxc-browser/_locales/de/messages.json
  keepassxc-browser/_locales/el/messages.json
  keepassxc-browser/_locales/en_GB/messages.json
  keepassxc-browser/_locales/es/messages.json
  keepassxc-browser/_locales/fi/messages.json
  keepassxc-browser/_locales/fr/messages.json
  keepassxc-browser/_locales/he/messages.json
  keepassxc-browser/_locales/hu/messages.json
  keepassxc-browser/_locales/id/messages.json
  keepassxc-browser/_locales/it/messages.json
  keepassxc-browser/_locales/ja/messages.json
  keepassxc-browser/_locales/ko/messages.json
  keepassxc-browser/_locales/lt/messages.json
  keepassxc-browser/_locales/nb/messages.json
  keepassxc-browser/_locales/nl/messages.json
  keepassxc-browser/_locales/pl/messages.json
  keepassxc-browser/_locales/pt_BR/messages.json
  keepassxc-browser/_locales/pt_PT/messages.json
  keepassxc-browser/_locales/ro/messages.json
  keepassxc-browser/_locales/ru/messages.json
  keepassxc-browser/_locales/sv/messages.json
  keepassxc-browser/_locales/tr/messages.json
  keepassxc-browser/_locales/uk/messages.json
  keepassxc-browser/_locales/zh_CN/messages.json
  keepassxc-browser/_locales/zh_TW/messages.json
  package-lock.json
  package.json
Labels: release

#2657 Update manifest.json
  keepassxc-browser/manifest.json
Labels: release

#2659 Fix topmost element check with Shadow DOM
  keepassxc-browser/content/fields.js
Labels: bug
