Repository keepassxreboot/keepassxc-browser, pull requests merged in 2025-09, with the labels that each got.

#2667 Fix topmost input element check with labels
  .eslintrc
  keepassxc-browser/common/global.js
  keepassxc-browser/content/fields.js
Labels: bug, security

#2673 Fix Custom Login Fields with topmost element check
  keepassxc-browser/content/fields.js
Labels: bug

#2675 Update to 1.9.9.5
  CHANGELOG
  dist/manifest_chromium.json
  dist/manifest_firefox.json
  keepassxc-browser/manifest.json
  package-lock.json
  package.json
Labels: release

#2676 Protect against form overlays
  keepassxc-browser/content/fields.js
Labels: bug, security

#2682 Fix detecting existing combination
  keepassxc-browser/common/sites.js
  keepassxc-browser/content/fields.js
Labels: bug

#2635 Update observer-helper.js to handle mutations with multiple elements
  keepassxc-browser/content/observer-helper.js
Labels: enhancement

#2706 Change settings icon
  keepassxc-browser/options/options.html
Labels: enhancement
